schedule_read:
  description: >
    Answer the users question based on the IPL_Schedule.csv file provided.
    Look at the complete schedule always to answer the question.
    Look at {history} for the previous messages answered and to maintain context.
    Use future tense to answer the question.
    The schedule_expert agent will search through the CSV to find the relevant answers.
    Here is the users question: {input_from_user}
    The histroy of the chat is: {history}
    In histroy, key "role" contains 2 values - user and model.
    key "text" contains the message.
    If the "role" is user, the "text" contains the message of the user
    If the "role" is model, the "text" contains the message of the LLM Model

    The teams of the matches Qualifier 1, Qualifier 2, Eliminator and Final will be decided based on the results of the previous games.
    The top 4 teams will play these matches.

    The first row is the header row in the CSV file.
    The columns of the CSV file and the data they contain are

    Match No: The match number of IPL 2025
    Match Day: The day of the match since IPL 2025 has started. On some days, 2 matches are played, but at different times
    Date: The date when the match is played. It is in format DD-MMM-YY
    Day: The day of the week when the match is played. Only the first 3 characters of the day is shown. For example, Sunday is entered as Sun
    Start: The time of the match in 24 hour format
    Home: Team name at whose home the match is played. The Venue column depicts the home of the team
    Away: Team name who are playing the match. The match is played between the data in Home and Away
    Venue: The city in which the match is played. All the venues are in India.

    Examples:

    Example 1:
    User Input: Where is the first game played?
    Thought: The user is asking the venue of the first game
    Action: Search for Match No 1 from the IPL_Schedule.csv file and look at the Venue column
    Answer: The first game will be played in Kolkata

    Example 2:
    User Input: How many matches will be played in Mumbai?
    Thought: I need to find the number of matches played in Mumbai by looking at the Vendue column, filtering out for value Mumbai, and then counting the results
    Action: SELECT count(*) where venue = "Mumbai"
    Answer: There are 7 games that will be played in Mumbai

    Example 3:
    User Input: How many times will Chennai Super Kings and Mumbai Indians play against each other?
    Thought: I should look at the Home and Away columns for this information. I should find the matches where the Home team is Chennai Super Kings and Away team is
    Mumbai Indians, and also find matches where Home team is Mumbai Indians and Away team is Chennai Super Kings. I should then count the number of such results
    Answer: Chennai Super Kings and Mumbai Indians and will play against each other 2 times.

    Example 4:
    User Input: When is the first game in Ahmedabad?
    Thought: I need to find the first game played in Ahmedabad by searching the CSV file for the Venue column and looking for the first occurrence of "Ahmedabad".
    Answer: The first game in Ahmedabad will be on March 25th, 2025, at 7:30 PM between Gujarat Titans and Punjab Kings
  expected_output: >
    Your output should be a relevant, accurate, and engaging response that directly addresses the user's query or continues the conversation logically.
    If the information is not available in the CSV file, say "Sorry, I do not have the information."
    Talk to the user normally, in complete sentences

    Example 5:
    User Input: When is the first game?
    Thought: I need to find the date of the first game.  I will use the IPL Scheduler search tool to find the row with the lowest 'Match Day' value and extract the 'Date' from that row.
    Answer: The first game will be on March 22nd, 2025

    User Input: Where will it be played?
    History: [{'role': 'user', 'text': 'When is the first game?'}, {'role': 'model', 'text': 'The first game will be on March 22nd, 2025.'}
    Thought: I need to find the venue of the first game.  To do this, I will use the IPL Scheduler search tool to search for the first match in the schedule and extract the venue.
    Answer: The first game will be played in Kolkata.
  agent: schedule_expert